#
# G+smo Travis-CI YML script
#
# Travis CI is the primary CI service for macOS
#
# Author: Angelos Mantzaflaris 2012-2018
#

sudo: false

git:
  submodules: false

language: cpp

notifications:
  email: false

# The purpose of the different branches is as follows:
# - stable        : tests all commits to the stable branch with different macOS configurations and generates doxygen documentation
# - coverity_scan : performs a coverity scan of the source code (triggered by merging code into the branch 'coverity_scan')
# - ci_test       : performs more extensive CI tests (triggered by merging code into the branch 'ci_test').
branches:
  only:
  - stable
  - coverity_scan
  - ci_test

os: linux  # unless specified otherwise
dist: trusty
#group: travis_latest

env:
  global:
   - MAKEFLAGS=-j3
   - secure: "JU9XIrFb6n1IqFt5hxNldvLVYLStfippytPsUWP5OxSjlwh3KtZ1kYLOzjGy6BHgVLCk/N7rWBKPeYS/nA4bKrcTC/uFml1NU58uQQMWsLaI17XRV96tWOhfT4FCfD+3RW9B0IO9T8WAUggC1aiP/Ft0qUxdb8yQN3QNQpU7bQJtDbPhfsWI81fMEEAeeqHjHb3bG9LXuFdCQN378b0t6fLs+48G4ECmwD48UAmFfI4Ral5a89dOR3yi2eQNtDoBNjLAC/oaimpmK//V/UYlHkZDsg+K0W04UcDgh173Pa/JAlx+aROICkmhs+n8YndB3qsXgT0iI/yiAaeUgkssjBh3Cs/r21C2tv2S7hs9nfiIsCc8bToxPg1QMCMENvjaNt5ZKmeCsqSaHQkS7RhiNnSvDS0qw/q89dpApcxfslDP72GTvOruqGdruQfcenBaJpdqMgijfIY9lBlsmwp0YX7Knq0zbSjL7CaDF6TpIPLRIt2njcfTr+IzVjIoS/Yv8rAFMCBPkbZG61E5GA6d77R+gzSHjYe0SAm+1HHV4MfvS4kLrfRbAR0k7mArOXlm2f87rCaf5rX1TBt7kaJOT2nmkeFbm8PkvbG05Iv2Hx2yXC4PvK0o/riy3uI6CipK84sO066detTbHRfMvMbVjNl/68VuFcGeNaa6YyshpVE="

addons:
  coverity_scan:
    project:
      name: "gismo/gismo"
      description: "Build submitted via Travis CI"
    notification_email: filiatra@gmail.com
    build_command_prepend: "cmake ."
    build_command:   "make"
    branch_pattern: coverity_scan

###################
matrix:
  fast_finish: true
  include:

    - os: osx
      if: branch = stable
      osx_image: xcode9.4 # macOS 10.13 (High Sierra)
      compiler: clang
      env:
        - COMPILER=clang++
        - BUILD_TYPE=Release
        - CXX_STANDARD=98
   
    - os: osx
      if: branch = stable
      osx_image: xcode10.3 # macOS 10.14.4 (Mojave)
      compiler: clang
      env:
        - COMPILER=clang++
        - BUILD_TYPE=Release
        - CXX_STANDARD=11
        
    - os: osx
      if: branch = stable
      osx_image: xcode11.6 # macOS 10.15.5 (Catalina)
      compiler: clang
      env:
        - COMPILER=clang++
        - BUILD_TYPE=Release
        - CXX_STANDARD=14

    - if: branch = stable
      compiler: gcc
      addons:
        apt:
          packages:
            - doxygen
            - doxygen-latex
            - texlive-binaries
            - graphviz
          sources:
            - sourceline: ppa:libreoffice/libreoffice-4-2 # for doxygen 1.8
            - ubuntu-toolchain-r-test
      env:
        - BUILD_TYPE=Release
        - TASK=Doxygen
        - CXX_STANDARD=98
      #install:
        #- wget -q 'https://github.com/doxygen/doxygen/archive/master.tar.gz' -O doxygen.tar.gz
        #- tar -xzf doxygen.tar.gz; mv doxygen-* doxygen
        #- pushd doxygen && cmake -G "Unix Makefiles" . -DCMAKE_RULE_MESSAGES=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr && make && sudo make install && popd

    - os: osx
      if: branch = ci_test
      osx_image: xcode9.4 # macOS 10.13 (High Sierra)
      compiler: clang
      env:
        - COMPILER=clang++
        - BUILD_TYPE=Release

    - os: osx
      if: branch = ci_test
      osx_image: xcode9.4 # macOS 10.13 (High Sierra)
      compiler: clang
      env:
        - COMPILER=clang++
        - BUILD_TYPE=RelWithDebInfo

    - env: COMPILER=g++-6 BUILD_TYPE=Release
      if: branch = ci_test OR branch = coverity_scan
      addons: &gcc6
        apt:
          packages: g++-6
          sources:
            - ubuntu-toolchain-r-test
      before_install:
        - pip install --user cpp-coveralls
      before_script:
        - mkdir build; cd build; cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_STANDARD=$CXX_STANDARD -DGISMO_WITH_ONURBS=ON -DGISMO_BUILD_UNITTESTS=ON -DSITE="$TRAVIS_BRANCH/travis-cov" -D
        ME="$TRAVIS_OS_NAME-$TRAVIS_COMPILER_cxx$CXX_STANDARD_$TRAVIS_CPU_ARCH" #-DGISMO_WITH_IPOPT=ON -DGISMO_BUILD_COVERAGE=ON
      after_success:
        - coveralls --exclude lib --exclude tests --gcov-options '\-lp'

    - env: COMPILER=g++-5 BUILD_TYPE=Release
      if: branch = ci_test
      addons: &gcc5
        apt:
          packages: g++-5
          sources:
            - ubuntu-toolchain-r-test


## .. artifacts ?

##################

before_install:
  - test $TRAVIS_BRANCH != coverity_scan -o ${TRAVIS_JOB_NUMBER##*.} = 1 || exit 0
  - if [ "$TRAVIS_OS_NAME" == "osx" && "$TRAVIS_OSX_IMAGE" == "xcode9.4" ]; then brew update>/dev/null; brew install valgrind; fi #--HEAD
  #- echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

before_script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then mkdir build; cd build; cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_STANDARD=$CXX_STANDARD -DGISMO_WITH_ONURBS=ON -DGISMO_BUILD_UNITTESTS=ON -DSITE="$TRAVIS_PULL_REQUEST-$TRAVIS_PULL_REQUEST_BRANCH [travis]" -DBUILDNAME="$TRAVIS_OS_NAME-$TRAVIS_OSX_IMAGE_$TRAVIS_COMPILER_cxx$CXX_STANDARD_$TRAVIS_CPU_ARCH"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then mkdir build; cd build; cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_STANDARD=$CXX_STANDARD -DGISMO_WITH_ONURBS=ON -DGISMO_BUILD_UNITTESTS=ON -DSITE="$TRAVIS_PULL_REQUEST-$TRAVIS_PULL_REQUEST_BRANCH [travis]" -DBUILDNAME="$TRAVIS_OS_NAME-$TRAVIS_COMPILER_cxx$CXX_STANDARD_$TRAVIS_CPU_ARCH"; fi

script:
  - if [ -e "cov-int/scm_log.txt" ]; then cat cov-int/scm_log.txt; fi
  - ctest $MAKEFLAGS --output-on-failure -C %BUILD_TYPE% -D ExperimentalStart -D ExperimentalConfigure -D ExperimentalBuild -D ExperimentalTest
  - if [ $TRAVIS_BRANCH != stable ] && [ $TASK != Doxygen ]; then ctest $MAKEFLAGS --output-on-failure -D ExperimentalMemCheck; fi
  - if [ "$TASK" != "Doxygen" ]; then ctest -D ExperimentalSubmit; fi

before_deploy:
  - make doc
  - ctest --add-notes doc/doxygen.log -M Experimental -T Submit

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  repo: gismo/gismo.github.io
  target-branch: master
  local-dir: build/doc/html
  #verbose: true
  on:
    branch: stable
    condition: $TASK = Doxygen
